// Generated by gen_data.py. Edit there, not here.
window.WALK_DATA = {
  "title": "The walk",
  "subtitle": "Sample readings, 8 of the 45 points, in the order an inspector takes them",
  "ariaLabel": "An inspector's walk through a kitchen: eight sample readings from the 45-point check, four pass, two need action this week, two today.",
  "key": [
    {
      "state": "pass",
      "label": "Pass"
    },
    {
      "state": "week",
      "label": "This week"
    },
    {
      "state": "today",
      "label": "Today"
    }
  ],
  "countFormat": "{points} points · {pass} pass · {week} this week · {today} today",
  "points": [
    {
      "n": 1,
      "label": "Entrance",
      "icon": "entrance",
      "reading": "Allergen folder at the till",
      "state": "pass"
    },
    {
      "n": 2,
      "label": "Chill display",
      "icon": "chill",
      "reading": "8.7°C, above 5°C",
      "state": "today"
    },
    {
      "n": 3,
      "label": "Hand-wash sink",
      "icon": "handwash",
      "reading": "Soap, towels, hot water",
      "state": "pass"
    },
    {
      "n": 4,
      "label": "Cook line",
      "icon": "cookline",
      "reading": "Chicken core 78°C",
      "state": "pass"
    },
    {
      "n": 5,
      "label": "Prep",
      "icon": "prep",
      "reading": "Raw stored above ready-to-eat",
      "state": "today"
    },
    {
      "n": 6,
      "label": "Walk-in",
      "icon": "walkin",
      "reading": "3.9°C, probe calibrated",
      "state": "pass"
    },
    {
      "n": 7,
      "label": "Dry store",
      "icon": "drystore",
      "reading": "Opened bag, no label or date",
      "state": "week"
    },
    {
      "n": 8,
      "label": "Back door",
      "icon": "backdoor",
      "reading": "Brush strip gap 8 mm",
      "state": "week"
    }
  ],
  "icons": {
    "entrance": "<rect x=\"2\" y=\"2\" width=\"36\" height=\"24\" rx=\"2\"/><path d=\"M2 14h10\"/><path d=\"M12 8v12\"/><path d=\"M12 14a8 8 0 0 1 8 8\" stroke-dasharray=\"2 2\"/>",
    "chill": "<rect x=\"2\" y=\"6\" width=\"36\" height=\"16\" rx=\"2\"/><path d=\"M2 12h36\"/><path d=\"M8 6V3h24v3\"/><path d=\"M12 16h4M20 16h4M28 16h4\"/>",
    "handwash": "<rect x=\"8\" y=\"6\" width=\"24\" height=\"16\" rx=\"3\"/><circle cx=\"20\" cy=\"14\" r=\"4\"/><path d=\"M20 2v4\"/><path d=\"M14 22v4M26 22v4\"/>",
    "cookline": "<rect x=\"2\" y=\"8\" width=\"36\" height=\"14\" rx=\"1\"/><circle cx=\"9\" cy=\"15\" r=\"3\"/><circle cx=\"18\" cy=\"15\" r=\"3\"/><rect x=\"25\" y=\"11\" width=\"10\" height=\"8\"/><path d=\"M6 4h28\" stroke-dasharray=\"3 2\"/>",
    "prep": "<rect x=\"2\" y=\"9\" width=\"36\" height=\"6\" rx=\"1\"/><path d=\"M6 15v9M34 15v9\"/><rect x=\"10\" y=\"3\" width=\"8\" height=\"6\"/><rect x=\"22\" y=\"3\" width=\"8\" height=\"6\"/>",
    "walkin": "<rect x=\"4\" y=\"2\" width=\"32\" height=\"24\" rx=\"2\"/><path d=\"M4 9h32\"/><path d=\"M14 9v17\"/><path d=\"M11 17v3\"/><path d=\"M22 14h8M22 18h8\"/>",
    "drystore": "<rect x=\"3\" y=\"2\" width=\"34\" height=\"24\" rx=\"1\"/><path d=\"M3 10h34M3 18h34\"/><path d=\"M9 6v4M17 6v4M25 6v4M11 14v4M21 14v4M29 22v4\"/>",
    "backdoor": "<rect x=\"2\" y=\"2\" width=\"20\" height=\"24\" rx=\"2\"/><path d=\"M22 14h5\"/><path d=\"M2 26h20\" stroke-width=\"3\"/><rect x=\"29\" y=\"14\" width=\"9\" height=\"12\" rx=\"1\"/><path d=\"M27 14h13\"/>"
  },
  "timing": {
    "rest": 1200,
    "firstReading": 2000,
    "beat": 2200,
    "redHold": 600,
    "draw": 500,
    "settle": 150,
    "rise": 400,
    "done": 19000,
    "hold": 21000,
    "resetStart": 23000,
    "loop": 24000
  }
};
